version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        PROJECT_DIR: /workspace
    environment:
      PATH: /home/user/.nix-profile/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin
      USE_NIX_SHELL: "true"
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - direnv-allow:/home/user/.config/direnv/allow
      - nix:/nix
    security_opt:
      - label:disable
    network_mode: "bridge"

volumes:
  nix:
  direnv-allow:
